const API_URL = `${import.meta.env.VITE_BASE_URL}/${import.meta.env.VITE_API_BASE_URL}/auth`;

function getRedirectUri() {
  return import.meta.env.VITE_OAUTH_REDIRECT_URI ||
    `${window.location.origin}${import.meta.env.BASE_URL || '/'}#/callback`;
}

const STATE_KEY = 'oauth_state';
const RETURN_PATH_KEY = 'oauth_return_path';

// CSRF/CS (OAuth state) protection: generate a one-time opaque value, validate on return.
export function generateState() {
  const arr = new Uint8Array(16);
  window.crypto.getRandomValues(arr);
  return Array.from(arr, dec2hex).join('');
}

/**
 * Helper to handle fetch responses
 */
async function handleResponse(response) {
  const text = await response.text();
  const data = text ? JSON.parse(text) : {};

  if (!response.ok) {
    const error = (data && data.message) || response.statusText;
    throw new Error(error);
  }
  return data;
}

function dec2hex(dec) {
  return dec.toString(16).padStart(2, '0');
}

export function generateCodeVerifier() {
  const array = new Uint32Array(56 / 2);
  window.crypto.getRandomValues(array);
  return Array.from(array, dec2hex).join('');
}

function base64urlencode(a) {
  let str = "";
  let bytes = new Uint8Array(a);
  let len = bytes.byteLength;
  for (let i = 0; i < len; i++) {
    str += String.fromCharCode(bytes[i]);
  }
  return btoa(str)
    .replace(/\+/g, "-")
    .replace(/\//g, "_")
    .replace(/=+$/, "");
}

export async function generateCodeChallenge(v) {
  const encoder = new TextEncoder();
  const data = encoder.encode(v);
  const hashed = await window.crypto.subtle.digest('SHA-256', data);
  return base64urlencode(hashed);
}

export const initiateSSO = async (returnPath = '/') => {
  const clientId = import.meta.env.VITE_OAUTH_CLIENT_ID || 'verbapix_vue';
  const redirectUri = getRedirectUri();
  
  const verifier = generateCodeVerifier();
  localStorage.setItem('pkce_verifier', verifier);

  const challenge = await generateCodeChallenge(verifier);
  const state = generateState();
  localStorage.setItem(STATE_KEY, state);
  localStorage.setItem(RETURN_PATH_KEY, returnPath.startsWith('/') ? returnPath : '/');

  const authUrl = new URL(`${API_URL}/authorize`);
  authUrl.searchParams.append('client_id', clientId);
  authUrl.searchParams.append('redirect_uri', redirectUri);
  authUrl.searchParams.append('response_type', 'code');
  authUrl.searchParams.append('code_challenge', challenge);
  authUrl.searchParams.append('code_challenge_method', 'S256');
  authUrl.searchParams.append('state', state);
  
  window.location.href = authUrl.toString();
};

export const consumeAuthReturnPath = () => {
  const path = localStorage.getItem(RETURN_PATH_KEY) || '/';
  localStorage.removeItem(RETURN_PATH_KEY);
  return path.startsWith('/') ? path : '/';
};

export const exchangeAuthCode = async (code) => {
  const clientId = import.meta.env.VITE_OAUTH_CLIENT_ID || 'verbapix_vue';
  const redirectUri = getRedirectUri();
  const verifier = localStorage.getItem('pkce_verifier');
  
  if (!verifier) {
    throw new Error('No PKCE verifier found in storage');
  }

  const response = await fetch(`${API_URL}/token`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      auth_code: code,
      client_id: clientId,
      redirect_uri: redirectUri,
      code_verifier: verifier
    })
  });
  
  const data = await handleResponse(response);
  
  if (data.access_token || data.token) {
    localStorage.setItem('auth_token', data.access_token || data.token);
    if (data.refresh_token) localStorage.setItem('refresh_token', data.refresh_token);
    localStorage.setItem('user_data', JSON.stringify(data.user));
    
    // Clear verifier after successful exchange
    localStorage.removeItem('pkce_verifier');
    localStorage.removeItem(STATE_KEY);
  }
  
  return data;
};

/**
 * Validate an OAuth state value against the one generated by initiateSSO.
 * Returns true when they match (or when no state was issued and none expected).
 */
export const validateAuthState = (state) => {
  const expected = localStorage.getItem(STATE_KEY);
  if (!expected) return state == null; // no flow in progress → nothing to check
  if (!state) return false;
  return state === expected;
};

/**
 * Single callback handler. Both AuthCallback.vue and any legacy Home flow call
 * this so the exchange + state-check + hydration logic lives in one place.
 * Returns the normalized user object when successful.
 */
export const handleAuthCallback = async (code, state) => {
  if (!code) throw new Error('No authorization code found in URL.');
  if (!validateAuthState(state)) throw new Error('OAuth state mismatch (possible CSRF).');

  const data = await exchangeAuthCode(code);
  if (!data.user) throw new Error('User data not found in response');

  return {
    id: data.user.id || data.user.uid,
    name: data.user.name || data.user.displayName || 'Player',
    photo: { src: data.user.photoURL || data.user.avatar || '' },
    level: data.user.level || 0
  };
};

/**
 * Authorized fetch with token refresh + one retry on 401.
 * Callers use this for GVPixel/API calls that require auth.
 */
export const authedFetch = async (url, options = {}) => {
  const doFetch = (_retried) => {
    const headers = { ...(options.headers || {}), 'Content-Type': 'application/json' };
    const token = localStorage.getItem('auth_token');
    if (token) headers['Authorization'] = `Bearer ${token}`;
    return fetch(url, { ...options, headers });
  };

  let response = await doFetch(false);
  if (response.status === 401 && !response.url.includes('/token') && !response.url.includes('/refresh')) {
    await refreshToken().catch(() => {/* refresh failed; the retry below surfaces the original 401 */});
    response = await doFetch(true);
  }
  return response;
};

export const logout = async () => {
  localStorage.removeItem('auth_token');
  localStorage.removeItem('refresh_token');
  localStorage.removeItem('user_data');
  return Promise.resolve();
};

export const refreshToken = async () => {
  const refresh_token = localStorage.getItem('refresh_token');
  if (!refresh_token) throw new Error('No refresh token available');

  const response = await fetch(`${API_URL}/refresh`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ refresh_token })
  });

  const data = await handleResponse(response);
  if (data.access_token) {
    localStorage.setItem('auth_token', data.access_token);
  }
  return data;
};

export const getCurrentUser = () => {
  const userStr = localStorage.getItem('user_data');
  return userStr ? JSON.parse(userStr) : null;
};

export const getAuthToken = () => {
  return localStorage.getItem('auth_token');
};

export const checkAuth = async () => {
  // Ensure we have a token before asking, or maybe the cookie is HttpOnly?
  // The user said "redirect to base_url + /login". This usually implies a cookie-based SSO or similar, OR we get a token back in URL.
  // BUT, usually if we redirect, we return with a token or code.
  // HOWEVER, the instruction "check the authorization from the base url" might mean fetch /me with credentials.
  // Given current `auth.js` uses Bearer tokens in localStorage, I will assume the external login sets the cookie or we need to fetch /me.
  // Actually, if we redirect to `base_url/login`, we might expect to be redirected BACK with a token?
  // User instruction is vague: "check the authorization from the base url".
  // If I look at the `register` and `login` functions, they expect JSON response with token.
  // If I redirect to a page, I'm not getting a JSON response directly in JS.
  // Use case: User clicks login -> goes to external site -> logs in -> redirects back to app (implied) -> App checks "Am I logged in?".
  // So `checkAuth` should probably hit an endpoint that returns the user if the session (cookie) is valid OR if the URL param has a token.
  // Since I don't see URL param parsing in the plan, I'll stick to hitting the API.
  // Use `handleResponse` which is already defined.

  const response = await fetch(`${API_URL}/me`, {
    method: 'GET',
    headers: {
      'Content-Type': 'application/json',
      // existing logic uses token from local storage, but if we just logged in externally, we might not have it yet?
      // Unless the external login writes to localStorage (impossible across domains) or sets a cookie.
      // I will verify if I should include 'Authorization': `Bearer ...`
      // If the redirect flow happens, the user comes back.
      // If the user said "check authorization from base url", it likely means "call the API to see if we are authorized".
      // I will try to use the token if it exists, or credentials include if cookie based.
      // Safe bet: Try to get current token.
      ...(localStorage.getItem('auth_token') ? { 'Authorization': `Bearer ${localStorage.getItem('auth_token')}` } : {})
    }
  });

  // If response is 401, handleResponse throws.
  return await handleResponse(response);
};
